export const QUESTION_TEXT_MAX_CHARS = 1_200;
export const CONCISE_ANSWER_MAX_CHARS = 800;
export const QUESTION_PROVENANCE_MAX_CHARS = 360;
export const QUESTION_GENERATION_DEFAULT_COUNT = 5;
export const QUESTION_GENERATION_MAX_COUNT = 10;
export const QUESTION_ADD_MAX_COUNT = 80;
