import assert from "node:assert/strict";
import { evaluateRecall } from "../app/lib/v2/model.ts";
import { evaluateRecallWithRetries } from "../app/lib/v2/recallEvaluation.ts";
import { resolveOpenRouterApiKey } from "../shared/openrouter-config.mts";

if (process.env.DATABASE_URL || process.env.DATABASE_URL_UNPOOLED) {
  throw new Error(
    "Refusing to run the recall evaluator smoke test with database access.",
  );
}
if (!resolveOpenRouterApiKey()) {
  throw new Error("OPENROUTER_API_KEY or LLM_API_KEY is required.");
}

type RecallResult = "incorrect" | "partial" | "correct";
type SmokeCase = {
  name: string;
  prompt: string;
  referenceAnswer: string;
  answer: string;
  expected: RecallResult;
};

const returnPrompt =
  "What is the formula for the discounted return G_t from time step t?";
const returnStandard =
  "G_t = Σ_(k=0)^∞ γ^k R_(t+k+1), or G_t = Σ_(l=0)^(T-t-1) γ^l r_(t+l) for finite T, where γ ∈ [0, 1) is the discount factor and R is the reward.";
const cases: SmokeCase[] = [
  {
    name: "exact formula without supporting definitions",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer: "G_t = Σ_(k=0)^∞ γ^k R_(t+k+1).",
    expected: "correct",
  },
  {
    name: "finite-horizon alternative",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer: "For an episode ending at T, G_t = Σ_(l=0)^(T-t-1) γ^l r_(t+l).",
    expected: "correct",
  },
  {
    name: "equivalent prose representation",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer:
      "Add future rewards, weighting the reward k steps ahead by gamma to the kth power, with weight one on the immediate next reward.",
    expected: "correct",
  },
  {
    name: "discount omitted",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer: "G_t is the sum of all future rewards after time t.",
    expected: "partial",
  },
  {
    name: "off-by-one exponent",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer: "G_t = Σ_(k=0)^∞ γ^(k+1) R_(t+k+1).",
    expected: "partial",
  },
  {
    name: "wrong quantity",
    prompt: returnPrompt,
    referenceAnswer: returnStandard,
    answer: "G_t is the probability that the episode terminates at time t.",
    expected: "incorrect",
  },
  {
    name: "central distinction contradicted",
    prompt:
      "What distinction separates an online reinforcement-learning algorithm from an on-policy reinforcement-learning algorithm?",
    referenceAnswer:
      "Online concerns updating as data is actively collected rather than from a fixed offline dataset. On-policy concerns whether update data was generated by the current target policy rather than another behavior policy.",
    answer:
      "They are synonyms: both mean updating continuously from data generated by the current policy.",
    expected: "incorrect",
  },
  {
    name: "one requested distinction omitted",
    prompt:
      "What distinction separates an online reinforcement-learning algorithm from an on-policy reinforcement-learning algorithm?",
    referenceAnswer:
      "Online concerns updating as data is actively collected rather than from a fixed offline dataset. On-policy concerns whether update data was generated by the current target policy rather than another behavior policy.",
    answer:
      "Online RL updates incrementally from interactions being collected rather than a fixed offline dataset.",
    expected: "partial",
  },
];

const results = [];
for (const smokeCase of cases) {
  const evaluation = await evaluateRecallWithRetries({
    prompt: smokeCase.prompt,
    evaluate: () =>
      evaluateRecall({
        userId: "recall-evaluator-smoke-no-persist",
        prompt: smokeCase.prompt,
        referenceAnswer: smokeCase.referenceAnswer,
        answer: smokeCase.answer,
      }),
  });
  results.push({
    name: smokeCase.name,
    expected: smokeCase.expected,
    actual: evaluation.recallResult,
    confidence: evaluation.confidence,
  });
}

for (const result of results) {
  assert.equal(
    result.actual,
    result.expected,
    `${result.name}: expected ${result.expected}, received ${result.actual}`,
  );
  assert.equal(typeof result.confidence, "number");
}

let retryProbeCalls = 0;
const retryProbe = await evaluateRecallWithRetries({
  prompt: "Verify retry behavior without persisting evidence.",
  evaluate: async () => {
    retryProbeCalls += 1;
    if (retryProbeCalls === 1) {
      throw new Error("Synthetic transport failure.");
    }
    if (retryProbeCalls === 2) {
      throw new Error("Synthetic parsing failure.");
    }
    return {
      recallResult: "correct",
      coveredPoints: ["Retryable failures were recovered"],
      scoringIssues: [],
      clarifications: [],
      confidence: 0,
    };
  },
});
assert.equal(retryProbeCalls, 3);
assert.equal(retryProbe.recallResult, "correct");
assert.equal(retryProbe.confidence, 0);

console.log(
  JSON.stringify(
    {
      passed: results.length,
      retryProbe: { calls: retryProbeCalls, confidence: retryProbe.confidence },
      results,
    },
    null,
    2,
  ),
);
